### ISSUE TITLE
Line endings for sscanApp/Db/scanProgress.db and sscanApp/src/scanProg.st

### ISSUE THREAD

**Issue by hinxx** [epics-modules/sscan#11]
If I crate a branch on forked repo and try to checkout the branch afterwards I get these error messages:

```
error: Your local changes to the following files would be overwritten by checkout:
	sscanApp/Db/scanProgress.db
	sscanApp/src/scanProg.st
Please, commit your changes or stash them before you can switch branches.
Aborting

```

It turns out that the line endings want to be different on my Linux system.

```
warning: CRLF will be replaced by LF in sscanApp/Db/scanProgress.db.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in sscanApp/src/scanProg.st.
The file will have its original line endings in your working directory.
```

It does not happen with any other epics-modules/<pkg>.

Would maintainer consider fixing the two files in question?

**Comment by hinxx** [comment]
FYI, I already tried with all git config core.autocrlf settings but the result is always the same.
the only thing that works for me is to commit changed files to master and then merge into desired branch.

**Comment by MarkRivers** [comment]
I have the same problems with my git clone of this repository.

**Comment by timmmooney** [comment]
Done.  Thanks, guys.

**Comment by hinxx** [comment]
Checkout does not change line endings anymore! Solved for me.. Thanks!
