### ISSUE TITLE
Record "SSCAN-EX:ScanDimH1" is of unknown type "scalcout"

### ISSUE THREAD

**Issue by Baokangwen** [epics-modules/sscan#31]
@hanak @ralphlange @jlmuir @prjemian 
I run ioc has an error:Record "SSCAN-EX:ScanDimH1" is of unknown type "scalcout"
Error at or before ")" in file "/home/guest/EPICS/synApps_6_1/supports_6_1/support/sscan/sscanApp/Db/standardScans.db" line 220
Error: syntax error
dbLoadRecords:failed to load /home/guest/EPICS/synApps_6_1/supports_6_1/support/sscan/sscanApp/Db/standardScans.db

**Comment by ralphlange** [comment]
The sscan module depends on the calc module. (Which contains the scalcout record.)

**Comment by Baokangwen** [comment]
@ralphlange 
I added calc, but it still same error, it doesn't seem to be the reason.

**Comment by MarkRivers** [comment]
You need to add both the dbd and library files for calc to your IOC Makefile.

**Comment by MarkRivers** [comment]
myApp_LIBS += calc
myApp_DBD += calcSupport.dbd

**Comment by Baokangwen** [comment]
@MarkRivers 
Thank you Mark.
I know how to do this.
